import json
from typing import Dict, Any
from langgraph.graph import END

LOW_CONFIDENCE_THRESHOLD = 0.75

async def review_routing_node(state: Dict[str, Any]) -> Dict[str, Any]:
    """
    Halts the pipeline and writes reasons to the review_queue if confidence is below threshold.
    """
    db_pool = state["db_pool"]
    workflow_run_id = state["workflow_run_id"]
    document_id = state.get("document_id")
    
    extraction_result = state.get("extraction_result", {})
    extraction_conf = extraction_result.get("extraction_confidence", 1.0)
    
    async with db_pool.acquire() as conn:
        async with conn.transaction():
            # 1. Update workflow_run status
            await conn.execute(
                "UPDATE workflow_runs SET status = 'PARTIAL' WHERE id = $1",
                workflow_run_id
            )
            
            # 2. Check extraction confidence
            if extraction_conf < LOW_CONFIDENCE_THRESHOLD:
                reason = f"Extraction confidence {extraction_conf} is below threshold of {LOW_CONFIDENCE_THRESHOLD}."
                await conn.execute(
                    """
                    INSERT INTO review_queue (document_id, screening_result_id, reason, status)
                    VALUES ($1, NULL, $2, 'OPEN')
                    """,
                    document_id, reason
                )
                
            # 3. Check screening confidence by querying the database directly
            # This cleanly grabs the IDs generated by the screening node without altering its schema
            low_conf_results = await conn.fetch(
                """
                SELECT sr.id, sr.confidence, c.name as component_name, i.canonical_name as ingredient_name, r.code as reg_code
                FROM screening_results sr
                JOIN components c ON sr.component_id = c.id
                JOIN ingredients i ON sr.ingredient_id = i.id
                JOIN regulations r ON sr.regulation_id = r.id
                WHERE sr.workflow_run_id = $1 AND sr.confidence < $2
                """,
                workflow_run_id, LOW_CONFIDENCE_THRESHOLD
            )
            
            for row in low_conf_results:
                reason = f"Screening confidence {row['confidence']} for {row['ingredient_name']} (in {row['component_name']}) under {row['reg_code']} is below threshold."
                await conn.execute(
                    """
                    INSERT INTO review_queue (document_id, screening_result_id, reason, status)
                    VALUES ($1, $2, $3, 'OPEN')
                    """,
                    document_id, row['id'], reason
                )
                
    return state
